// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: echo.proto

package com.twitter.finagle.protobuf.test;

public final class Echo {
  private Echo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EchoRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string phrase = 1;
    boolean hasPhrase();
    String getPhrase();
  }
  public static final class EchoRequest extends
      com.google.protobuf.GeneratedMessage
      implements EchoRequestOrBuilder {
    // Use EchoRequest.newBuilder() to construct.
    private EchoRequest(Builder builder) {
      super(builder);
    }
    private EchoRequest(boolean noInit) {}

    private static final EchoRequest defaultInstance;
    public static EchoRequest getDefaultInstance() {
      return defaultInstance;
    }

    public EchoRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.twitter.finagle.protobuf.test.Echo.internal_static_com_twitter_finagle_protobuf_test_EchoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.twitter.finagle.protobuf.test.Echo.internal_static_com_twitter_finagle_protobuf_test_EchoRequest_fieldAccessorTable;
    }

    private int bitField0_;
    // optional string phrase = 1;
    public static final int PHRASE_FIELD_NUMBER = 1;
    private java.lang.Object phrase_;
    public boolean hasPhrase() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPhrase() {
      java.lang.Object ref = phrase_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          phrase_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPhraseBytes() {
      java.lang.Object ref = phrase_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        phrase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      phrase_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPhraseBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPhraseBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.twitter.finagle.protobuf.test.Echo.EchoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.twitter.finagle.protobuf.test.Echo.EchoRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.twitter.finagle.protobuf.test.Echo.EchoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.twitter.finagle.protobuf.test.Echo.internal_static_com_twitter_finagle_protobuf_test_EchoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.twitter.finagle.protobuf.test.Echo.internal_static_com_twitter_finagle_protobuf_test_EchoRequest_fieldAccessorTable;
      }

      // Construct using com.twitter.finagle.protobuf.test.Echo.EchoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        phrase_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.twitter.finagle.protobuf.test.Echo.EchoRequest.getDescriptor();
      }

      public com.twitter.finagle.protobuf.test.Echo.EchoRequest getDefaultInstanceForType() {
        return com.twitter.finagle.protobuf.test.Echo.EchoRequest.getDefaultInstance();
      }

      public com.twitter.finagle.protobuf.test.Echo.EchoRequest build() {
        com.twitter.finagle.protobuf.test.Echo.EchoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private com.twitter.finagle.protobuf.test.Echo.EchoRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.twitter.finagle.protobuf.test.Echo.EchoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public com.twitter.finagle.protobuf.test.Echo.EchoRequest buildPartial() {
        com.twitter.finagle.protobuf.test.Echo.EchoRequest result = new com.twitter.finagle.protobuf.test.Echo.EchoRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.phrase_ = phrase_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.twitter.finagle.protobuf.test.Echo.EchoRequest) {
          return mergeFrom((com.twitter.finagle.protobuf.test.Echo.EchoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.twitter.finagle.protobuf.test.Echo.EchoRequest other) {
        if (other == com.twitter.finagle.protobuf.test.Echo.EchoRequest.getDefaultInstance()) return this;
        if (other.hasPhrase()) {
          setPhrase(other.getPhrase());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              phrase_ = input.readBytes();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // optional string phrase = 1;
      private java.lang.Object phrase_ = "";
      public boolean hasPhrase() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPhrase() {
        java.lang.Object ref = phrase_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          phrase_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPhrase(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        phrase_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhrase() {
        bitField0_ = (bitField0_ & ~0x00000001);
        phrase_ = getDefaultInstance().getPhrase();
        onChanged();
        return this;
      }
      void setPhrase(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        phrase_ = value;
        onChanged();
      }

      // @@protoc_insertion_point(builder_scope:com.twitter.finagle.protobuf.test.EchoRequest)
    }

    static {
      defaultInstance = new EchoRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.twitter.finagle.protobuf.test.EchoRequest)
  }

  public interface EchoResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string error = 1;
    boolean hasError();
    String getError();

    // optional string phrase = 2;
    boolean hasPhrase();
    String getPhrase();
  }
  public static final class EchoResponse extends
      com.google.protobuf.GeneratedMessage
      implements EchoResponseOrBuilder {
    // Use EchoResponse.newBuilder() to construct.
    private EchoResponse(Builder builder) {
      super(builder);
    }
    private EchoResponse(boolean noInit) {}

    private static final EchoResponse defaultInstance;
    public static EchoResponse getDefaultInstance() {
      return defaultInstance;
    }

    public EchoResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.twitter.finagle.protobuf.test.Echo.internal_static_com_twitter_finagle_protobuf_test_EchoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.twitter.finagle.protobuf.test.Echo.internal_static_com_twitter_finagle_protobuf_test_EchoResponse_fieldAccessorTable;
    }

    private int bitField0_;
    // optional string error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private java.lang.Object error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          error_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string phrase = 2;
    public static final int PHRASE_FIELD_NUMBER = 2;
    private java.lang.Object phrase_;
    public boolean hasPhrase() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getPhrase() {
      java.lang.Object ref = phrase_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          phrase_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPhraseBytes() {
      java.lang.Object ref = phrase_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        phrase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      error_ = "";
      phrase_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getErrorBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPhraseBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getErrorBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPhraseBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.twitter.finagle.protobuf.test.Echo.EchoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.twitter.finagle.protobuf.test.Echo.EchoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.twitter.finagle.protobuf.test.Echo.EchoResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.twitter.finagle.protobuf.test.Echo.EchoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.twitter.finagle.protobuf.test.Echo.internal_static_com_twitter_finagle_protobuf_test_EchoResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.twitter.finagle.protobuf.test.Echo.internal_static_com_twitter_finagle_protobuf_test_EchoResponse_fieldAccessorTable;
      }

      // Construct using com.twitter.finagle.protobuf.test.Echo.EchoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        phrase_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.twitter.finagle.protobuf.test.Echo.EchoResponse.getDescriptor();
      }

      public com.twitter.finagle.protobuf.test.Echo.EchoResponse getDefaultInstanceForType() {
        return com.twitter.finagle.protobuf.test.Echo.EchoResponse.getDefaultInstance();
      }

      public com.twitter.finagle.protobuf.test.Echo.EchoResponse build() {
        com.twitter.finagle.protobuf.test.Echo.EchoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      private com.twitter.finagle.protobuf.test.Echo.EchoResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.twitter.finagle.protobuf.test.Echo.EchoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }

      public com.twitter.finagle.protobuf.test.Echo.EchoResponse buildPartial() {
        com.twitter.finagle.protobuf.test.Echo.EchoResponse result = new com.twitter.finagle.protobuf.test.Echo.EchoResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.phrase_ = phrase_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.twitter.finagle.protobuf.test.Echo.EchoResponse) {
          return mergeFrom((com.twitter.finagle.protobuf.test.Echo.EchoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.twitter.finagle.protobuf.test.Echo.EchoResponse other) {
        if (other == com.twitter.finagle.protobuf.test.Echo.EchoResponse.getDefaultInstance()) return this;
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasPhrase()) {
          setPhrase(other.getPhrase());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              error_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              phrase_ = input.readBytes();
              break;
            }
          }
        }
      }

      private int bitField0_;

      // optional string error = 1;
      private java.lang.Object error_ = "";
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setError(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      void setError(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
      }

      // optional string phrase = 2;
      private java.lang.Object phrase_ = "";
      public boolean hasPhrase() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getPhrase() {
        java.lang.Object ref = phrase_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          phrase_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPhrase(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        phrase_ = value;
        onChanged();
        return this;
      }
      public Builder clearPhrase() {
        bitField0_ = (bitField0_ & ~0x00000002);
        phrase_ = getDefaultInstance().getPhrase();
        onChanged();
        return this;
      }
      void setPhrase(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        phrase_ = value;
        onChanged();
      }

      // @@protoc_insertion_point(builder_scope:com.twitter.finagle.protobuf.test.EchoResponse)
    }

    static {
      defaultInstance = new EchoResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.twitter.finagle.protobuf.test.EchoResponse)
  }

  public static abstract class EchoService
      implements com.google.protobuf.Service {
    protected EchoService() {}

    public interface Interface {
      public abstract void echo(
          com.google.protobuf.RpcController controller,
          com.twitter.finagle.protobuf.test.Echo.EchoRequest request,
          com.google.protobuf.RpcCallback<com.twitter.finagle.protobuf.test.Echo.EchoResponse> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new EchoService() {
        @java.lang.Override
        public  void echo(
            com.google.protobuf.RpcController controller,
            com.twitter.finagle.protobuf.test.Echo.EchoRequest request,
            com.google.protobuf.RpcCallback<com.twitter.finagle.protobuf.test.Echo.EchoResponse> done) {
          impl.echo(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.echo(controller, (com.twitter.finagle.protobuf.test.Echo.EchoRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.twitter.finagle.protobuf.test.Echo.EchoRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return com.twitter.finagle.protobuf.test.Echo.EchoResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }

      };
    }

    public abstract void echo(
        com.google.protobuf.RpcController controller,
        com.twitter.finagle.protobuf.test.Echo.EchoRequest request,
        com.google.protobuf.RpcCallback<com.twitter.finagle.protobuf.test.Echo.EchoResponse> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return com.twitter.finagle.protobuf.test.Echo.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.echo(controller, (com.twitter.finagle.protobuf.test.Echo.EchoRequest)request,
            com.google.protobuf.RpcUtil.<com.twitter.finagle.protobuf.test.Echo.EchoResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.twitter.finagle.protobuf.test.Echo.EchoRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return com.twitter.finagle.protobuf.test.Echo.EchoResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends com.twitter.finagle.protobuf.test.Echo.EchoService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void echo(
          com.google.protobuf.RpcController controller,
          com.twitter.finagle.protobuf.test.Echo.EchoRequest request,
          com.google.protobuf.RpcCallback<com.twitter.finagle.protobuf.test.Echo.EchoResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.twitter.finagle.protobuf.test.Echo.EchoResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            com.twitter.finagle.protobuf.test.Echo.EchoResponse.class,
            com.twitter.finagle.protobuf.test.Echo.EchoResponse.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public com.twitter.finagle.protobuf.test.Echo.EchoResponse echo(
          com.google.protobuf.RpcController controller,
          com.twitter.finagle.protobuf.test.Echo.EchoRequest request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public com.twitter.finagle.protobuf.test.Echo.EchoResponse echo(
          com.google.protobuf.RpcController controller,
          com.twitter.finagle.protobuf.test.Echo.EchoRequest request)
          throws com.google.protobuf.ServiceException {
        return (com.twitter.finagle.protobuf.test.Echo.EchoResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          com.twitter.finagle.protobuf.test.Echo.EchoResponse.getDefaultInstance());
      }

    }
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_twitter_finagle_protobuf_test_EchoRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_twitter_finagle_protobuf_test_EchoRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_twitter_finagle_protobuf_test_EchoResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_twitter_finagle_protobuf_test_EchoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\necho.proto\022!com.twitter.finagle.protob" +
      "uf.test\"\035\n\013EchoRequest\022\016\n\006phrase\030\001 \001(\t\"-" +
      "\n\014EchoResponse\022\r\n\005error\030\001 \001(\t\022\016\n\006phrase\030" +
      "\002 \001(\t2v\n\013EchoService\022g\n\004Echo\022..com.twitt" +
      "er.finagle.protobuf.test.EchoRequest\032/.c" +
      "om.twitter.finagle.protobuf.test.EchoRes" +
      "ponseB\003\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_twitter_finagle_protobuf_test_EchoRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_twitter_finagle_protobuf_test_EchoRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_twitter_finagle_protobuf_test_EchoRequest_descriptor,
              new java.lang.String[] { "Phrase", },
              com.twitter.finagle.protobuf.test.Echo.EchoRequest.class,
              com.twitter.finagle.protobuf.test.Echo.EchoRequest.Builder.class);
          internal_static_com_twitter_finagle_protobuf_test_EchoResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_twitter_finagle_protobuf_test_EchoResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_twitter_finagle_protobuf_test_EchoResponse_descriptor,
              new java.lang.String[] { "Error", "Phrase", },
              com.twitter.finagle.protobuf.test.Echo.EchoResponse.class,
              com.twitter.finagle.protobuf.test.Echo.EchoResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
